"""Added time of last access

Revision ID: 2dd925b37d6a
Revises: 9d63b2b59b2f
Create Date: 2025-11-17 19:39:39.464987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd925b37d6a'
down_revision = '9d63b2b59b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_access', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_column('last_access')

    # ### end Alembic commands ###
